import type { Hospitalization } from "./types"

export const mockHospitalizations: Hospitalization[] = [
  {
    id: "hosp1",
    petId: "1",
    clientId: "1",
    admissionDate: "2024-11-10T08:00:00Z",
    reason: "Cirugía de esterilización",
    diagnosis: "Ovariohisterectomía programada",
    treatment: "Pre-operatorio: ayuno 12h, fluidoterapia IV. Post-operatorio: antibióticos (Amoxicilina 20mg/kg cada 12h), analgésicos (Meloxicam 0.1mg/kg cada 24h), control de herida quirúrgica.",
    status: "active",
    veterinarianId: "2",
    room: "Sala 1",
    notes: "Mascota tranquila, recuperación normal",
    studies: [
      {
        id: "study1",
        hospitalizationId: "hosp1",
        type: "blood_test",
        name: "Hemograma completo",
        date: "2024-11-10T07:00:00Z",
        results: "Valores dentro de parámetros normales. Hemoglobina: 15.2 g/dL, Hematocrito: 45%, Leucocitos: 8.5 x 10³/μL",
        performedBy: "Dr. Carlos Ruiz",
      },
      {
        id: "study2",
        hospitalizationId: "hosp1",
        type: "blood_test",
        name: "Perfil bioquímico",
        date: "2024-11-10T07:15:00Z",
        results: "Función renal y hepática normal. Glucosa: 95 mg/dL, Creatinina: 1.1 mg/dL",
        performedBy: "Dr. Carlos Ruiz",
      },
    ],
    vitalSigns: [
      {
        date: "2024-11-10T08:00:00Z",
        temperature: 38.5,
        heartRate: 95,
        respiratoryRate: 20,
        weight: 30,
        notes: "Pre-operatorio",
      },
      {
        date: "2024-11-10T14:00:00Z",
        temperature: 38.2,
        heartRate: 88,
        respiratoryRate: 18,
        notes: "Post-operatorio inmediato",
      },
      {
        date: "2024-11-11T08:00:00Z",
        temperature: 38.3,
        heartRate: 90,
        respiratoryRate: 19,
        notes: "Recuperación estable",
      },
    ],
  },
  {
    id: "hosp2",
    petId: "3",
    clientId: "2",
    admissionDate: "2024-11-09T10:00:00Z",
    reason: "Tratamiento de gastroenteritis",
    diagnosis: "Gastroenteritis aguda de origen bacteriano",
    treatment: "Fluidoterapia IV (Ringer Lactato 50ml/kg/día), antibióticos (Metronidazol 15mg/kg cada 12h), protectores gástricos (Omeprazol 1mg/kg cada 24h), dieta blanda progresiva.",
    status: "active",
    veterinarianId: "2",
    room: "Sala 2",
    notes: "Mejoría progresiva, tolerando alimento",
    studies: [
      {
        id: "study3",
        hospitalizationId: "hosp2",
        type: "blood_test",
        name: "Hemograma y bioquímica",
        date: "2024-11-09T10:30:00Z",
        results: "Leucocitosis leve (12.5 x 10³/μL), deshidratación moderada. Electrolitos dentro de rango.",
        performedBy: "Dr. Carlos Ruiz",
      },
      {
        id: "study4",
        hospitalizationId: "hosp2",
        type: "xray",
        name: "Radiografía abdominal",
        date: "2024-11-09T11:00:00Z",
        results: "No se observan cuerpos extraños. Ligera distensión gástrica, compatible con gastroenteritis.",
        performedBy: "Dr. Carlos Ruiz",
      },
    ],
    vitalSigns: [
      {
        date: "2024-11-09T10:00:00Z",
        temperature: 39.2,
        heartRate: 110,
        respiratoryRate: 25,
        weight: 35,
        notes: "Admisión - deshidratado",
      },
      {
        date: "2024-11-10T10:00:00Z",
        temperature: 38.8,
        heartRate: 100,
        respiratoryRate: 22,
        notes: "Mejoría con fluidoterapia",
      },
      {
        date: "2024-11-11T10:00:00Z",
        temperature: 38.5,
        heartRate: 95,
        respiratoryRate: 20,
        notes: "Recuperación satisfactoria",
      },
    ],
  },
  {
    id: "hosp3",
    petId: "2",
    clientId: "1",
    admissionDate: "2024-11-08T09:00:00Z",
    dischargeDate: "2024-11-10T16:00:00Z",
    reason: "Control post-operatorio",
    diagnosis: "Recuperación post-esterilización",
    treatment: "Antibióticos, analgésicos, retiro de puntos quirúrgicos",
    status: "discharged",
    veterinarianId: "2",
    room: "Sala 1",
    notes: "Alta médica - recuperación completa",
    studies: [
      {
        id: "study5",
        hospitalizationId: "hosp3",
        type: "blood_test",
        name: "Control post-operatorio",
        date: "2024-11-10T15:00:00Z",
        results: "Valores normales, no signos de infección",
        performedBy: "Dr. Carlos Ruiz",
      },
    ],
    vitalSigns: [
      {
        date: "2024-11-10T16:00:00Z",
        temperature: 38.4,
        heartRate: 92,
        respiratoryRate: 20,
        weight: 4.5,
        notes: "Alta médica",
      },
    ],
  },
]

