import type { MarketplaceProduct } from "./types"

export const marketplaceProducts: MarketplaceProduct[] = [
  {
    id: "m1",
    name: "Alimento Premium para Perros",
    description: "Alimento completo y balanceado para perros adultos. 15kg",
    price: 45.99,
    image: "/images/dry-pet-food-toys-other-260nw-2373064631.webp",
    category: "food",
    stock: 50,
    rating: 4.5,
    reviews: 120,
  },
  {
    id: "m2",
    name: "Huesitos para Perros",
    description: "Huesitos naturales para masticar y limpiar dientes",
    price: 8.99,
    image: "/images/Huesitos.jpg",
    category: "food",
    stock: 45,
    rating: 4.7,
    reviews: 95,
  },
  {
    id: "m3",
    name: "Juguete para Mascotas",
    description: "Juguete resistente para entretenimiento canino y felino",
    price: 12.99,
    image: "/images/Juguete.jpg",
    category: "toys",
    stock: 80,
    rating: 4.3,
    reviews: 67,
  },
  {
    id: "m4",
    name: "Soga para Perros",
    description: "Soga resistente para juegos y ejercicios",
    price: 9.99,
    image: "/images/Soga.jpg",
    category: "toys",
    stock: 25,
    rating: 4.8,
    reviews: 145,
  },
  {
    id: "m5",
    name: "Collares para Mascotas",
    description: "Collares de nylon resistente con placa de identificación personalizable",
    price: 15.99,
    image: "/images/Collares.jpg",
    category: "accessories",
    stock: 100,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: "m6",
    name: "Correa con Pechera",
    description: "Correa ajustable con pechera cómoda para paseos",
    price: 24.99,
    image: "/images/CorreaPechera.jpg",
    category: "accessories",
    stock: 60,
    rating: 4.4,
    reviews: 112,
  },
  {
    id: "m7",
    name: "Shampoo para Mascotas",
    description: "Shampoo suave y nutritivo para el cuidado del pelaje. 500ml",
    price: 18.99,
    image: "/images/Shampoo.webp",
    category: "hygiene",
    stock: 75,
    rating: 4.5,
    reviews: 203,
  },
  {
    id: "m8",
    name: "Pasta de Dientes para Mascotas",
    description: "Kit completo con cepillo y pasta dental sabor a pollo",
    price: 9.99,
    image: "/images/PastaDientes.webp",
    category: "hygiene",
    stock: 90,
    rating: 4.2,
    reviews: 56,
  },
  {
    id: "m9",
    name: "Cama para Mascotas",
    description: "Cama cómoda y acogedora. Tamaño grande",
    price: 89.99,
    image: "/images/Camita.jpeg",
    category: "accessories",
    stock: 30,
    rating: 4.9,
    reviews: 78,
  },
  {
    id: "m10",
    name: "Mochila Transportadora",
    description: "Mochila transportadora cómoda y segura para viajes",
    price: 45.99,
    image: "/images/Mochila.jpg",
    category: "accessories",
    stock: 40,
    rating: 4.6,
    reviews: 94,
  },
  {
    id: "m11",
    name: "Jaula para Mascotas",
    description: "Jaula espaciosa y segura para transporte y descanso",
    price: 79.99,
    image: "/images/Jaula.jpg",
    category: "accessories",
    stock: 20,
    rating: 4.7,
    reviews: 156,
  },
  {
    id: "m12",
    name: "Antipulgas",
    description: "Tratamiento antipulgas y garrapatas. Efectivo y duradero",
    price: 22.99,
    image: "/images/antipulga.webp",
    category: "medicine",
    stock: 55,
    rating: 4.4,
    reviews: 88,
  },
  {
    id: "m13",
    name: "Pipeta Antipulgas",
    description: "Pipeta antipulgas y garrapatas de larga duración",
    price: 19.99,
    image: "/images/pipeta.webp",
    category: "medicine",
    stock: 65,
    rating: 4.6,
    reviews: 142,
  },
  {
    id: "m14",
    name: "Pipeta Premium",
    description: "Pipeta de acción prolongada contra parásitos externos",
    price: 24.99,
    image: "/images/pipeta2.webp",
    category: "medicine",
    stock: 50,
    rating: 4.8,
    reviews: 98,
  },
  {
    id: "m15",
    name: "Cepillo para Pelo",
    description: "Cepillo profesional para el cuidado del pelaje",
    price: 14.99,
    image: "/images/CepilloPelo.webp",
    category: "hygiene",
    stock: 70,
    rating: 4.5,
    reviews: 115,
  },
  {
    id: "m16",
    name: "Guantes para Pelo",
    description: "Guantes especiales para eliminar pelo suelto",
    price: 11.99,
    image: "/images/guantespelo.webp",
    category: "hygiene",
    stock: 85,
    rating: 4.3,
    reviews: 76,
  },
  {
    id: "m17",
    name: "Secador para Mascotas",
    description: "Secador profesional de bajo ruido para baños",
    price: 69.99,
    image: "/images/Secador.jpg",
    category: "hygiene",
    stock: 15,
    rating: 4.7,
    reviews: 89,
  },
  {
    id: "m18",
    name: "Ropa para Mascotas",
    description: "Ropa cómoda y abrigada para perros y gatos",
    price: 29.99,
    image: "/images/Ropa.webp",
    category: "accessories",
    stock: 45,
    rating: 4.4,
    reviews: 103,
  },
  {
    id: "m19",
    name: "Cucha para Gatos",
    description: "Cucha acogedora y cálida para gatos",
    price: 39.99,
    image: "/images/cuchagato.webp",
    category: "accessories",
    stock: 35,
    rating: 4.6,
    reviews: 67,
  },
  {
    id: "m20",
    name: "Cucha para Perros",
    description: "Cucha resistente y cómoda para perros",
    price: 49.99,
    image: "/images/cuchita.webp",
    category: "accessories",
    stock: 28,
    rating: 4.8,
    reviews: 92,
  },
  {
    id: "m21",
    name: "Cama Premium",
    description: "Cama ortopédica con memoria viscoelástica. Tamaño extra grande",
    price: 99.99,
    image: "/images/Camita2.jpg",
    category: "accessories",
    stock: 18,
    rating: 4.9,
    reviews: 54,
  },
  {
    id: "m22",
    name: "Ropa de Abrigo",
    description: "Ropa de invierno para mascotas pequeñas y medianas",
    price: 34.99,
    image: "/images/Ropa3.jpeg",
    category: "accessories",
    stock: 32,
    rating: 4.5,
    reviews: 81,
  },
  {
    id: "m23",
    name: "Pasta Dental Premium",
    description: "Pasta dental enzimática para cuidado dental avanzado",
    price: 12.99,
    image: "/images/Pasta2.webp",
    category: "hygiene",
    stock: 55,
    rating: 4.7,
    reviews: 64,
  },
  {
    id: "m24",
    name: "Alimento Premium para Gatos",
    description: "Alimento completo y balanceado para gatos adultos. 10kg",
    price: 38.99,
    image: "/images/Alimentogato.avif",
    category: "food",
    stock: 42,
    rating: 4.6,
    reviews: 108,
  },
  {
    id: "m25",
    name: "Paseador para Perros",
    description: "Paseador ergonómico y cómodo para paseos diarios",
    price: 19.99,
    image: "/images/Paseador%20de%20perros.jpg",
    category: "accessories",
    stock: 55,
    rating: 4.5,
    reviews: 87,
  },
  {
    id: "m26",
    name: "Talco para Mascotas",
    description: "Talco suave para el cuidado de la piel y el pelaje",
    price: 7.99,
    image: "/images/Talco.webp",
    category: "hygiene",
    stock: 95,
    rating: 4.3,
    reviews: 72,
  },
  {
    id: "m27",
    name: "Toallitas Húmedas para Mascotas",
    description: "Toallitas limpiadoras para higiene diaria. Pack de 80 unidades",
    price: 6.99,
    image: "/images/Toallitas.webp",
    category: "hygiene",
    stock: 120,
    rating: 4.4,
    reviews: 156,
  },
]

