// Mock data for demonstration
import type { Client, Pet, MedicalRecord, Appointment, InventoryItem } from "./types"

export const mockClients: Client[] = [
  {
    id: "1",
    name: "Ana Martínez",
    email: "ana.martinez@email.com",
    phone: "+34 600 111 222",
    address: "Calle Mayor 123",
    city: "Madrid",
    postalCode: "28001",
    registrationDate: "2024-01-15",
    notes: "Cliente preferente",
  },
  {
    id: "2",
    name: "Carlos López",
    email: "carlos.lopez@email.com",
    phone: "+34 600 333 444",
    address: "Avenida Principal 45",
    city: "Barcelona",
    postalCode: "08001",
    registrationDate: "2024-02-20",
  },
  {
    id: "3",
    name: "María García",
    email: "maria.garcia@email.com",
    phone: "+34 600 555 666",
    address: "Plaza España 7",
    city: "Valencia",
    postalCode: "46001",
    registrationDate: "2024-03-10",
  },
]

export const mockPets: Pet[] = [
  {
    id: "1",
    name: "Max",
    species: "Perro",
    breed: "Golden Retriever",
    birthDate: "2020-05-15",
    weight: 30,
    color: "Dorado",
    clientId: "1",
    microchipNumber: "123456789012345",
    notes: "Muy amigable",
    photo: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400&h=400&fit=crop",
  },
  {
    id: "2",
    name: "Luna",
    species: "Gato",
    breed: "Siamés",
    birthDate: "2021-08-20",
    weight: 4.5,
    color: "Crema y marrón",
    clientId: "1",
    microchipNumber: "987654321098765",
    photo: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=400&fit=crop",
  },
  {
    id: "3",
    name: "Rocky",
    species: "Perro",
    breed: "Pastor Alemán",
    birthDate: "2019-03-10",
    weight: 35,
    color: "Negro y marrón",
    clientId: "2",
    microchipNumber: "456789123456789",
    photo: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400&h=400&fit=crop",
  },
  {
    id: "4",
    name: "Mimi",
    species: "Gato",
    breed: "Persa",
    birthDate: "2022-01-05",
    weight: 3.8,
    color: "Blanco",
    clientId: "3",
    photo: "https://images.unsplash.com/photo-1548247416-ec66f4900b77?w=400&h=400&fit=crop",
  },
  {
    id: "5",
    name: "Donatello",
    species: "Tortuga",
    breed: "Tortuga de Agua",
    birthDate: "2018-06-12",
    weight: 1.2,
    color: "Verde oscuro",
    clientId: "2",
    notes: "Tortuga muy activa",
    photo: "https://media.istockphoto.com/id/1472360511/photo/close-up-view-of-a-galapagos-giant-tortoise.jpg?s=1024x1024&w=is&k=20&c=kR48JzkuHYFcrPXjaAmmPQnRMXxkOPeZh0PZ9c1FnAY=",
  },
  {
    id: "6",
    name: "Nibbles",
    species: "Hamster",
    breed: "Hamster Dorado",
    birthDate: "2023-03-20",
    weight: 0.15,
    color: "Dorado",
    clientId: "3",
    notes: "Muy sociable",
    photo: "https://media.istockphoto.com/id/91778222/photo/cute-hamster.jpg?s=1024x1024&w=is&k=20&c=bRd3cs3kLtftnBeN8gEF0dsZQSrN2LGXOd94b3bYoF0=",
  },
]

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: "1",
    petId: "1",
    date: "2024-11-01",
    veterinarianId: "2",
    reason: "Vacunación anual",
    diagnosis: "Estado de salud óptimo",
    treatment: "Vacuna antirrábica y polivalente",
    observations: "Mascota en excelente condición física",
    nextVisit: "2025-11-01",
  },
  {
    id: "2",
    petId: "1",
    date: "2024-09-15",
    veterinarianId: "2",
    reason: "Revisión general",
    diagnosis: "Leve sobrepeso",
    treatment: "Dieta balanceada recomendada",
    observations: "Reducir premios y aumentar ejercicio",
    nextVisit: "2024-12-15",
  },
  {
    id: "3",
    petId: "2",
    date: "2024-10-20",
    veterinarianId: "2",
    reason: "Esterilización",
    diagnosis: "Procedimiento exitoso",
    treatment: "Antibióticos y analgésicos post-operatorios",
    observations: "Recuperación normal, retirar puntos en 10 días",
    nextVisit: "2024-10-30",
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: "1",
    petId: "1",
    clientId: "1",
    veterinarianId: "2",
    date: "2024-11-15",
    time: "10:00",
    reason: "Revisión general",
    status: "confirmed",
    notes: "Traer cartilla de vacunación",
  },
  {
    id: "2",
    petId: "3",
    clientId: "2",
    veterinarianId: "2",
    date: "2024-11-15",
    time: "11:30",
    reason: "Vacunación",
    status: "pending",
  },
  {
    id: "3",
    petId: "2",
    clientId: "1",
    veterinarianId: "2",
    date: "2024-11-16",
    time: "09:00",
    reason: "Control post-operatorio",
    status: "confirmed",
  },
  {
    id: "4",
    petId: "4",
    clientId: "3",
    veterinarianId: "2",
    date: "2024-11-16",
    time: "15:00",
    reason: "Primera consulta",
    status: "pending",
  },
]

export const mockInventory: InventoryItem[] = [
  {
    id: "1",
    name: "Vacuna Antirrábica",
    category: "medicine",
    quantity: 45,
    minStock: 20,
    price: 25.5,
    supplier: "VetPharma",
    expiryDate: "2025-12-31",
  },
  {
    id: "2",
    name: "Antibiótico Amoxicilina",
    category: "medicine",
    quantity: 30,
    minStock: 15,
    price: 18.75,
    supplier: "MediVet",
    expiryDate: "2025-06-30",
  },
  {
    id: "3",
    name: "Jeringuillas 5ml",
    category: "supply",
    quantity: 200,
    minStock: 50,
    price: 0.35,
    supplier: "Suministros Médicos SA",
  },
  {
    id: "4",
    name: "Guantes Látex (caja 100)",
    category: "supply",
    quantity: 15,
    minStock: 10,
    price: 12.5,
    supplier: "Suministros Médicos SA",
  },
  {
    id: "5",
    name: "Alimento Premium Perros",
    category: "food",
    quantity: 80,
    minStock: 30,
    price: 45.0,
    supplier: "PetFood Distribución",
    expiryDate: "2025-08-31",
  },
]
